apiVersion: "templates.cloudbees.com/v1alpha1"
kind: "Catalog"
metadata:
  name: "test-catalog"
  displayName: "Test Catalog"
spec:
  templates:
    - name: "simple-test"
      description: "Simple test pipeline"
      url: "templates/simple-test.yaml"
