apiVersion: "templates.cloudbees.com/v1alpha1"
kind: "Template"
metadata:
  name: "simple-test"
spec:
  description: "Simple 1 stage Jenkinsfile"
  template: |
    pipeline {
      agent any
      stages {
        stage('Test') {
          steps {
            echo '✅ Simple pipeline is working!'
          }
        }
      }
    }
