apiVersion: "templates.cloudbees.com/v1alpha1"
kind: "Template"
metadata:
  name: "customer-portal-frontend"
spec:
  description: "Frontend pipeline for Customer Portal applications"
  parameters:
    - name: "REPO_URL"
      description: "Git repository URL"
      type: "string"
      required: true
    - name: "BRANCH"
      description: "Git branch to build"
      type: "string"
      default: "main"
    - name: "NODE_VERSION"
      description: "Node.js version"
      type: "string"
      default: "18"
  
  template: |
    pipeline {
      agent any
      
      parameters {
        string(name: 'REPO_URL', defaultValue: '', description: 'Git repository URL')
        string(name: 'BRANCH', defaultValue: 'main', description: 'Git branch to build')
        string(name: 'NODE_VERSION', defaultValue: '18', description: 'Node.js version')
      }
      
      stages {
        stage('Checkout') {
          steps {
            git branch: params.BRANCH, url: params.REPO_URL
          }
        }
        
        stage('Setup Node.js') {
          steps {
            nodejs(nodeJSInstallationName: 'NodeJS-${params.NODE_VERSION}') {
              sh 'node --version'
              sh 'npm --version'
            }
          }
        }
        
        stage('Install Dependencies') {
          steps {
            sh 'npm ci'
          }
        }
        
        stage('Lint') {
          steps {
            sh 'npm run lint'
          }
        }
        
        stage('Test') {
          steps {
            sh 'npm test'
          }
        }
        
        stage('Build') {
          steps {
            sh 'npm run build'
          }
        }
        
        stage('Deploy Preview') {
          steps {
            echo "Deploying to staging environment..."
            // Add your deployment steps here
          }
        }
      }
      
      post {
        always {
          cleanWs()
        }
        success {
          echo "Pipeline succeeded!"
        }
        failure {
          echo "Pipeline failed!"
        }
      }
    }
