apiVersion: "templates.cloudbees.com/v1alpha1"
kind: "Template"
metadata:
  name: "java-maven-pipeline"
spec:
  description: "Simple Java App With Maven"
  parameters:
    - name: "emailRecipient"
      type: "string"
      description: "Email address to be used for sending build notifications"
    - name: "github_repo"
      type: "string"
      description: "GitHub HTTPS repo endpoint"
    - name: "github_creds"
      type: "credentials"
      description: "GitHub Credentials ID"
  
  template: |
    pipeline {
      agent any
      
      parameters {
        string(name: 'emailRecipient', description: 'Email address for build notifications')
        string(name: 'github_repo', description: 'GitHub HTTPS repo endpoint')
        credentials(name: 'github_creds', description: 'GitHub Credentials ID')
      }
      
      stages {
        stage('Checkout') { 
          steps {
            git credentialsId: github_creds, url: github_repo
          }
        }
        stage('Build') { 
          steps {
            sh 'mvn -B -DskipTests clean package' 
          }
        }
      }

      post {
        success {  
          emailext (
            subject: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
            body: """<p>SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
              <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
            to: emailRecipient,
            from: "buildNotifications@emailaddress.com"
          )
        }

        failure {
          emailext (
            subject: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
            body: """<p>FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
              <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
            to: emailRecipient,
            from: "buildNotifications@emailaddress.com"
          )
        }
      }
    }
